### ISSUE TITLE
Feature request: package blip for HomeBrew

### ISSUE THREAD

**Issue by weakcamel** [neechbear/blip#4]
It would be super fantastic if there was a [Homebrew](https://brew.sh/) package of `blip`!

It would open up for blip the brand and exciting market of MacOS users!

**Comment by neechbear** [comment]
```
brew tap neechbear/tap
brew install blip
```

Your wish is my command.

I've created the tap. I'll populate it with a formula as soon as I have figured out how. (It installs into `/usr/local/Cellar/blip/0.10/lib/blip.bash` which isn't very convenient; trying to work out the right symlink or deployment cleverness from the Tap Cookbook documentation).

**Comment by neechbear** [comment]
As it turns out, libraries automagically get linked for free! (Who would have thunk it right?)

```
nicolaw@laptop: ~/src/homebrew-tap $ ls -al /usr/local/lib/blip.bash
lrwxr-xr-x  1 nicolaw  admin  33 18 Aug 22:06 /usr/local/lib/blip.bash@ -> ../Cellar/blip/0.10/lib/blip.bash
```

**Comment by weakcamel** [comment]
Woop woop! fantastic, many thanks!

Installation went flawlessly and the power of `cmdarg` and bash backtrace is now at the reach of my fingertips ;-)

I've also started realising just how *many* subtle differences are there between MacOS and Linux - no `getent`, no /proc etc. ... shame on Apple! ;). It's deffinitely too much to try to make up for in `blip` but if I stumble across something rough around the edges for Mac, I'll do my best to patch it.
